version: 0.0
os: linux
files:
  - source: docker-compose.yml
    destination: /home/ubuntu/app
files:
  - source: package.json
    destination: /home/ubuntu/app
hooks:
  ApplicationStart:
    - location: ./install.sh
      timeout: 900

